### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by exmex** [exmex/DCNC#1]
- [x] missions
- [ ] inventory
- [ ] shops
- [ ] rewards
- [x] character info
- [ ] garage / cars
- [ ] crews
- [ ] licenses
- [ ] friends
- [ ] parties
- [ ] rankings
- [ ] coupons
- [ ] gotcha
- [ ] rush time
- [ ] npcs
- [ ] battle zone
- [ ] delis
- [ ] patrol
- [ ] call signs
- [ ] neo

**Comment by exmex** [comment]
- [ ] [Source](https://github.com/exmex/DCMM/blob/master/src/GameServer/Network/Handlers/Game.cs#L197) broadcast only to users in same area
- [ ] [Source](https://github.com/exmex/DCMM/blob/master/src/GameServer/Network/Handlers/Game.cs#L205) broadcast only to users in same party
- [ ] [Source](https://github.com/exmex/DCMM/blob/master/src/GameServer/Network/Handlers/Game.cs#L209) broadcast only to users in same crew
- [ ]  [Source](https://github.com/exmex/DCMM/blob/master/src/GameServer/Network/Handlers/Game.cs#L241) Send data correspoding to the charname, not user
- [ ] [Source](https://github.com/exmex/DCMM/blob/master/src/GameServer/Network/Handlers/Game.cs#L408) Buy car still has not the correct structure.
- [ ] [Source](https://github.com/exmex/DCMM/blob/master/src/Shared/Network/Packets.cs#L19) Wrong Packet Size. CMD(86) CmdLen: : 56, AnalysisSize: 24
- [ ] [Source](https://github.com/exmex/DCMM/blob/master/src/Shared/Network/Packets.cs#L41) Wrong Packet Size. CMD(661) CmdLen: : 1177, AnalysisSize: 831
- [ ] [Source](https://github.com/exmex/DCMM/blob/master/src/Shared/Network/Packets.cs#L49) Wrong Packet Size. CMD(841) CmdLen: : 692, AnalysisSize: 393
- [ ] [Source](https://github.com/exmex/DCMM/blob/master/src/Shared/Network/Packets.cs#L52) Wrong Packet Size. CMD(1401) CmdLen: : 14, AnalysisSize: 12
- [ ] [Source](https://github.com/exmex/DCMM/blob/master/src/Shared/Network/Packets.cs#L307) Wrong Packet Size. CMD(993) CmdLen: : 11, AnalysisSize: 8
- [ ] [Source](https://github.com/exmex/DCMM/blob/master/src/Shared/Network/Packets.cs#L37) Wrong Packet Size. CMD(467) CmdLen: : 240, AnalysisSize: 196
